"""
Skills API endpoints
"""
from fastapi import APIRouter, Query, HTTPException
from typing import Optional, List
from app.models.skill import (
    Skill,
    SkillListResponse,
    SkillDetailResponse,
    SkillCategory,
    SkillCreate,
    SkillUpdate,
)

router = APIRouter()


# Mock data for development
MOCK_SKILLS = [
    Skill(
        id=1,
        name="Agent-SQL-Pro",
        description="Turn natural language into complex SQL queries instantly. Seamlessly integrate with PostgreSQL, MySQL, and Snowflake databases with read-only safety modes and intelligent query optimization.",
        category=SkillCategory.DATA_ANALYSIS,
        tags=["SQL", "Database", "Query"],
        author="AgenticX Team",
        version="2.4",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=184800,
        rating=4.9,
        review_count=2400,
        created_at="2024-01-15T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=2,
        name="Canvas Design",
        description="Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece.",
        category=SkillCategory.CONTENT_CREATION,
        tags=["Design", "Canvas", "Visual"],
        author="Design Pro",
        version="1.2",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=15000,
        rating=4.9,
        review_count=1200,
        created_at="2024-02-01T10:00:00Z",
        updated_at="2024-12-24T10:00:00Z",
    ),
    Skill(
        id=3,
        name="DOCX Editor",
        description="Comprehensive document creation, editing, and analysis with support for tracked changes, comments, formatting preservation, and text extraction.",
        category=SkillCategory.DEVELOPMENT,
        tags=["Document", "Word", "Editor"],
        author="Productivity Labs",
        version="1.5",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=28000,
        rating=4.8,
        review_count=2400,
        created_at="2024-01-20T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=4,
        name="PDF Toolkit",
        description="Comprehensive PDF manipulation toolkit for extracting text and tables, creating new PDFs, merging/splitting documents, and handling forms.",
        category=SkillCategory.DEVELOPMENT,
        tags=["PDF", "Document", "Toolkit"],
        author="PDF Master",
        version="2.1",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=32000,
        rating=4.6,
        review_count=2650,
        created_at="2024-01-10T10:00:00Z",
        updated_at="2024-12-23T10:00:00Z",
    ),
    Skill(
        id=5,
        name="PPTX Creator",
        description="Presentation creation, editing, and analysis. Create new presentations, modify content, work with layouts, and add comments or speaker notes.",
        category=SkillCategory.CONTENT_CREATION,
        tags=["Presentation", "PowerPoint", "PPT"],
        author="Office Tools",
        version="1.3",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=22000,
        rating=4.7,
        review_count=1850,
        created_at="2024-01-25T10:00:00Z",
        updated_at="2024-12-22T10:00:00Z",
    ),
    Skill(
        id=6,
        name="XLSX Master",
        description="Comprehensive spreadsheet creation, editing, and analysis with support for formulas, formatting, data analysis, and visualization.",
        category=SkillCategory.DATA_ANALYSIS,
        tags=["Excel", "Spreadsheet", "Data"],
        author="Data Tools",
        version="2.0",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=35000,
        rating=4.8,
        review_count=3100,
        created_at="2024-01-12T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=7,
        name="Frontend Design",
        description="Create distinctive, production-grade frontend interfaces with high design quality. Build web components, pages, artifacts with polished code and UI design.",
        category=SkillCategory.DEVELOPMENT,
        tags=["Frontend", "Web", "UI"],
        author="Web Dev Team",
        version="1.8",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=42000,
        rating=4.9,
        review_count=3850,
        created_at="2024-01-18T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=8,
        name="Slack GIF Creator",
        description="Create animated GIFs optimized for Slack with custom text, effects, and branding. Perfect for team communications and reactions.",
        category=SkillCategory.COMMUNICATION_COLLABORATION,
        tags=["GIF", "Slack", "Animation"],
        author="Team Tools",
        version="1.1",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=8500,
        rating=4.5,
        review_count=680,
        created_at="2024-02-10T10:00:00Z",
        updated_at="2024-12-22T10:00:00Z",
    ),
    Skill(
        id=9,
        name="WebApp Testing",
        description="Automated web application testing framework with support for functional, integration, and end-to-end testing scenarios.",
        category=SkillCategory.DEVELOPER_TOOLS,
        tags=["Testing", "Web", "Automation"],
        author="QA Team",
        version="1.4",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=18000,
        rating=4.7,
        review_count=1450,
        created_at="2024-01-28T10:00:00Z",
        updated_at="2024-12-23T10:00:00Z",
    ),
    Skill(
        id=10,
        name="Algorithmic Art",
        description="Generate stunning algorithmic and generative art using code. Create unique visual patterns, fractals, and mathematical beauty.",
        category=SkillCategory.CONTENT_CREATION,
        tags=["Art", "Algorithm", "Generative"],
        author="Creative Labs",
        version="1.0",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=12000,
        rating=4.8,
        review_count=980,
        created_at="2024-02-05T10:00:00Z",
        updated_at="2024-12-24T10:00:00Z",
    ),
    Skill(
        id=11,
        name="Internal Comms",
        description="Professional internal communications toolkit for creating company newsletters, updates, FAQs, and corporate messaging.",
        category=SkillCategory.COMMUNICATION_COLLABORATION,
        tags=["Communication", "Internal", "Corporate"],
        author="Comms Team",
        version="1.2",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=9200,
        rating=4.6,
        review_count=720,
        created_at="2024-02-08T10:00:00Z",
        updated_at="2024-12-21T10:00:00Z",
    ),
    Skill(
        id=12,
        name="MCP Builder",
        description="Model Context Protocol builder for creating AI agent integrations and custom tool connections. Extend AI capabilities with external services.",
        category=SkillCategory.DEVELOPER_TOOLS,
        tags=["MCP", "Protocol", "Integration"],
        author="MCP Team",
        version="2.0",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=25000,
        rating=4.9,
        review_count=2100,
        created_at="2024-01-22T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=13,
        name="Skill Creator",
        description="Meta-tool for creating new AI agent skills. Generate skill templates, documentation, and boilerplate code for custom capabilities.",
        category=SkillCategory.DEVELOPER_TOOLS,
        tags=["Meta", "Creator", "Template"],
        author="Dev Tools",
        version="1.1",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=14000,
        rating=4.7,
        review_count=1150,
        created_at="2024-02-03T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=14,
        name="Theme Factory",
        description="Generate beautiful, consistent design themes for your applications. Create color schemes, typography systems, and component styles.",
        category=SkillCategory.CONTENT_CREATION,
        tags=["Theme", "Design", "Styling"],
        author="Design Studio",
        version="1.3",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=19000,
        rating=4.8,
        review_count=1620,
        created_at="2024-01-30T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=15,
        name="Web Artifacts Builder",
        description="Build complete web artifacts including landing pages, portfolios, and interactive experiences with production-ready code.",
        category=SkillCategory.DEVELOPMENT,
        tags=["Web", "Artifacts", "Builder"],
        author="Web Studio",
        version="1.5",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=38000,
        rating=4.9,
        review_count=3250,
        created_at="2024-01-16T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=16,
        name="Brand Guidelines",
        description="Create comprehensive brand guideline documents including logos, colors, typography, and visual identity systems.",
        category=SkillCategory.CONTENT_CREATION,
        tags=["Brand", "Guidelines", "Identity"],
        author="Brand Team",
        version="1.0",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=11000,
        rating=4.7,
        review_count=890,
        created_at="2024-02-12T10:00:00Z",
        updated_at="2024-12-23T10:00:00Z",
    ),
    Skill(
        id=17,
        name="Doc Co-authoring",
        description="Collaborative document editing and co-authoring workflows for teams. Real-time editing, version control, and commenting.",
        category=SkillCategory.PRODUCTIVITY,
        tags=["Collaboration", "Document", "Co-authoring"],
        author="Collaboration Tools",
        version="1.2",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=7800,
        rating=4.5,
        review_count=640,
        created_at="2024-02-15T10:00:00Z",
        updated_at="2024-12-20T10:00:00Z",
    ),
    Skill(
        id=18,
        name="Deploying to Production",
        description="Automates GitHub repository creation and Vercel deployment for Next.js websites. Use when deploying new websites, pushing to production, setting up CI/CD pipelines.",
        category=SkillCategory.DEVELOPMENT,
        tags=["Deployment", "CI/CD", "Production"],
        author="DevOps Team",
        version="1.1",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=20000,
        rating=4.9,
        review_count=1680,
        created_at="2024-01-24T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=19,
        name="Doc Sync Tool",
        description="Automatically sync AI agent configuration documents (Agents.md, claude.md, gemini.md) across your project to maintain consistency.",
        category=SkillCategory.PRODUCTIVITY,
        tags=["Sync", "Document", "Config"],
        author="Dev Tools",
        version="1.0",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=5200,
        rating=4.6,
        review_count=420,
        created_at="2024-02-18T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=20,
        name="Google SEO Guide",
        description="Official Google SEO guide covering search optimization, best practices, Search Console, crawling, indexing, and improving website search visibility.",
        category=SkillCategory.DEVELOPMENT,
        tags=["SEO", "Google", "Search"],
        author="SEO Experts",
        version="2.1",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=45000,
        rating=4.9,
        review_count=3850,
        created_at="2024-01-14T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=21,
        name="Internationalizing Websites",
        description="Adds multi-language support to Next.js websites with proper SEO configuration including hreflang tags, localized sitemaps, and language-specific content.",
        category=SkillCategory.DEVELOPMENT,
        tags=["i18n", "Internationalization", "Multi-language"],
        author="Web Dev Team",
        version="1.4",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=28000,
        rating=4.8,
        review_count=2340,
        created_at="2024-01-19T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=22,
        name="ShipAny",
        description="AI-powered SaaS boilerplate documentation for Next.js 15, TypeScript, Drizzle ORM, NextAuth, and payment integration.",
        category=SkillCategory.DEVELOPMENT,
        tags=["SaaS", "Boilerplate", "Next.js"],
        author="SaaS Team",
        version="1.0",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=32000,
        rating=4.9,
        review_count=2750,
        created_at="2024-01-17T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=23,
        name="Web Performance SEO",
        description="Fix PageSpeed Insights accessibility audit errors, color contrast issues, and improve Core Web Vitals for better SEO rankings.",
        category=SkillCategory.DEVELOPMENT,
        tags=["Performance", "SEO", "Optimization"],
        author="Performance Team",
        version="1.2",
        llm_compatibility=["Claude 3"],
        is_free=True,
        download_count=18000,
        rating=4.7,
        review_count=1520,
        created_at="2024-01-26T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=24,
        name="ASR (Speech to Text)",
        description="Implement speech-to-text capabilities using z-ai-web-dev-sdk. Transcribe audio files, convert speech to text, and build voice input features.",
        category=SkillCategory.AI_AUDIO,
        tags=["ASR", "Speech", "Audio"],
        author="AI Audio Team",
        version="1.1",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=12000,
        rating=4.8,
        review_count=980,
        created_at="2024-02-01T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=25,
        name="LLM Chat",
        description="Implement large language model chat completions. Build conversational AI, chatbots, and text generation features with multi-turn conversations.",
        category=SkillCategory.AI_AUDIO,
        tags=["LLM", "Chat", "Conversation"],
        author="AI Team",
        version="2.0",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=25000,
        rating=4.9,
        review_count=2100,
        created_at="2024-01-21T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=26,
        name="TTS (Text to Speech)",
        description="Implement text-to-speech capabilities. Convert text into natural-sounding speech with multiple voices, adjustable speed, and various formats.",
        category=SkillCategory.AI_AUDIO,
        tags=["TTS", "Speech", "Audio"],
        author="AI Audio Team",
        version="1.3",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=10000,
        rating=4.7,
        review_count=850,
        created_at="2024-02-04T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=27,
        name="VLM (Vision Chat)",
        description="Implement vision-based AI chat capabilities. Analyze images, describe visual content, and combine image understanding with conversational AI.",
        category=SkillCategory.AI_AUDIO,
        tags=["VLM", "Vision", "Image"],
        author="Vision AI Team",
        version="1.2",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=15000,
        rating=4.8,
        review_count=1250,
        created_at="2024-01-29T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=28,
        name="Web Search",
        description="Implement web search capabilities. Retrieve current information, find relevant content, and build applications with real-time web search.",
        category=SkillCategory.WEB_TOOLS,
        tags=["Search", "Web", "Information"],
        author="Search Team",
        version="1.5",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=22000,
        rating=4.9,
        review_count=1850,
        created_at="2024-01-23T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=29,
        name="Web Reader",
        description="Implement web page content extraction. Scrape web pages, extract article content, retrieve page metadata, and process web content.",
        category=SkillCategory.WEB_TOOLS,
        tags=["Reader", "Web", "Scraping"],
        author="Web Tools",
        version="1.2",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=9500,
        rating=4.6,
        review_count=720,
        created_at="2024-02-06T10:00:00Z",
        updated_at="2024-12-25T10:00:00Z",
    ),
    Skill(
        id=30,
        name="AI Image Generation",
        description="Implement AI-powered image generation. Create images from text descriptions, generate visual content, and build AI-powered creative tools.",
        category=SkillCategory.AI_MEDIA,
        tags=["Image", "Generation", "AI"],
        author="AI Media Team",
        version="2.1",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=35000,
        rating=4.9,
        review_count=2950,
        created_at="2024-01-13T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
    Skill(
        id=31,
        name="AI Video Generation",
        description="Implement AI-powered video generation. Generate videos from text prompts or images with customizable resolution, frame rate, and duration.",
        category=SkillCategory.AI_MEDIA,
        tags=["Video", "Generation", "AI"],
        author="AI Media Team",
        version="1.4",
        llm_compatibility=["GPT-4o"],
        is_free=True,
        download_count=18000,
        rating=4.7,
        review_count=1450,
        created_at="2024-01-27T10:00:00Z",
        updated_at="2024-12-26T10:00:00Z",
    ),
]


@router.get("/", response_model=SkillListResponse)
async def list_skills(
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    category: Optional[SkillCategory] = None,
    search: Optional[str] = None,
    sort_by: str = Query("most_popular", regex="^(most_popular|newest|highest_rated)$"),
):
    """
    List all skills with pagination and filtering
    """
    skills = MOCK_SKILLS.copy()
    
    # Filter by category
    if category:
        skills = [s for s in skills if s.category == category]
    
    # Search
    if search:
        search_lower = search.lower()
        skills = [
            s for s in skills
            if search_lower in s.name.lower() or search_lower in s.description.lower()
        ]
    
    # Sort
    if sort_by == "newest":
        skills.sort(key=lambda x: x.created_at, reverse=True)
    elif sort_by == "highest_rated":
        skills.sort(key=lambda x: x.rating, reverse=True)
    else:  # most_popular
        skills.sort(key=lambda x: x.download_count, reverse=True)
    
    # Paginate
    total = len(skills)
    start = (page - 1) * page_size
    end = start + page_size
    paginated_skills = skills[start:end]
    
    return SkillListResponse(
        skills=paginated_skills,
        total=total,
        page=page,
        page_size=page_size,
    )


@router.get("/{skill_id}", response_model=SkillDetailResponse)
async def get_skill(skill_id: int):
    """
    Get skill details by ID
    """
    skill = next((s for s in MOCK_SKILLS if s.id == skill_id), None)
    if not skill:
        raise HTTPException(status_code=404, detail="Skill not found")
    
    # Add detail fields
    detail = SkillDetailResponse(
        **skill.dict(),
        readme=f"# {skill.name}\n\n{skill.description}\n\n## Installation\n\n```bash\npip install {skill.name.lower().replace(' ', '-')}\n```",
        installation_guide=f"Install {skill.name} using pip or download from the marketplace.",
        usage_examples=[
            f"Example 1: Use {skill.name} to perform basic operations",
            f"Example 2: Advanced usage of {skill.name}",
        ],
    )
    
    return detail


@router.post("/", response_model=Skill)
async def create_skill(skill: SkillCreate):
    """
    Create a new skill (requires authentication)
    """
    # TODO: Implement authentication and database persistence
    new_skill = Skill(
        id=len(MOCK_SKILLS) + 1,
        **skill.dict(),
        download_count=0,
        rating=0.0,
        review_count=0,
        created_at="2024-12-27T10:00:00Z",
        updated_at="2024-12-27T10:00:00Z",
    )
    MOCK_SKILLS.append(new_skill)
    return new_skill


@router.get("/trending/list")
async def get_trending_skills():
    """
    Get trending skills
    """
    # Return top skills by download count
    trending = sorted(MOCK_SKILLS, key=lambda x: x.download_count, reverse=True)[:5]
    return {"skills": trending}
